name: 'dbt_project'
version: '1.0.0'

profile: 'dbt_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  dbt_project:
    staging:
      +materialized: view
      +schema : STAGING
    marts:

      facts: 
        +materialized: table
        +schema : ANALYTICS

      dimensions : 
        +materialized: table
        +schema : ANALYTICS

